version: '3'

services:
  client:
    build:
      context: .
      dockerfile: client.Dockerfile
    ports:
      - 80:80
    restart: on-failure
  redis:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    expose:
      - 6379
    restart: always
    volumes:
      - redis-data:/data
    restart: on-failure
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: teamapp
    expose:
      - 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: on-failure
  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - 8080:8080
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    env_file:
      - ormconfig.env
      - ipcconfig.env
    environment:
      API_PORT: 3000
    ports:
      - 3000:3000
    depends_on:
      - redis
      - postgres
    links:
      - redis
      - postgres
    restart: on-failure

volumes:
  redis-data:
  postgres-data:
